var single = {
  "day": "Tuesday",
  "level": "Beginner",
  "team": "Test Team",
  "time": "4:00pm",
  "number": "1",
  "cost": 8000,
  "leads": 38,
  "follows": 40,
  "cap": 80,
  "location": "Test Location",
}

var multi = [
  {
    "day": "Sunday",
    "level": "Beginner",
    "team": "Ilona & Kris",
    "time": "2:00pm",
    "number": "8",
    "cost": 10000,
    "leads": 38,
    "follows": 40,
    "cap": 80,
    "location": "GPUC",
  },
  {
    "day": "Monday",
    "level": "Beginner Half-Class",
    "team": "Bernadette & Gee",
    "time": "6:30pm",
    "number": "19",
    "cost": 6000,
    "leads": 41,
    "follows": 38,
    "cap": 80,
    "location": "Trinity Orthodox Hall",
  },
  {
    "day": "Tuesday",
    "level": "Advanced",
    "team": "Shirley & Don",
    "time": "8:00pm",
    "number": "7",
    "cost": 15000,
    "leads": 29,
    "follows": 29,
    "cap": 60,
    "location": "Grosvenor Park",
  },
  {
    "day": "Wednesday",
    "level": "Intermediate Plus",
    "team": "Ev & Kris",
    "time": "8:15pm",
    "number": "14",
    "cost": 12500,
    "leads": 36,
    "follows": 33,
    "cap": 70,
    "location": "St. Joe's Hall",
  },
  {
    "day": "Wednesday",
    "level": "Intermediate",
    "team": "Bernadette & Gee",
    "time": "6:30pm",
    "number": "12",
    "cost": 12500,
    "leads": 36,
    "follows": 34,
    "cap": 70,
    "location": "Trinity Orthodox Hall",
  },
  {
    "day": "Wednesday",
    "level": "Beginner",
    "team": "Margie & Dale",
    "time": "7:00pm",
    "number": "13",
    "cost": 10000,
    "leads": 41,
    "follows": 39,
    "cap": 80,
    "location": "Grosvenor Park",
  }
]

export {
  single,
  multi,
}